### PR TITLE
Initial setup for downloading link shapefile and transforming it into pg_dump compatible with schema experiment

### PR DESCRIPTION
**Pull request by jarkkoka**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2)

### CODE REVIEW

**Review by lassemaatta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @haphut and @jarkkoka)

___
*[create_digiroad_pgdump.sh, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVoto9V2q9CxA0pjRRP:-MVoto9WCjDSvBHPrbfY:b-xqcsfo) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/4138802715a52e9d408496f26546adf9c4a7d63b/create_digiroad_pgdump.sh#L9)):*
> ```Shell
> 
> # Stop on first error.
> set -e
> ```

Tässä on aika monta muuttujaa, pitäiskö tässä olla `-eu`? (sama koskee noita muitakin `.sh` skriptejä)
___
*[create_digiroad_pgdump.sh, line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVouEDg-gmwe24gD9e9:-MVouEDg-gmwe24gD9eA:boxiu2p) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/4138802715a52e9d408496f26546adf9c4a7d63b/create_digiroad_pgdump.sh#L31)):*
> ```Shell
> # Remove possibly running/existing Docker container.
> set +e
> docker kill $DOCKER_CONTAINER_NAME &> /dev/null
> ```

kenties `|| true` voisi korvata nuo `set +e` lipun nollailut?
___
*[create_digiroad_pgdump.sh, line 48 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVovc-m2v-sMPvf_o5P:-MVovc-m2v-sMPvf_o5Q:bk7qs72) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/4138802715a52e9d408496f26546adf9c4a7d63b/create_digiroad_pgdump.sh#L48)):*
> ```
> import
> ```

Voisko tää olla vaikka `dr_import` tai `digiroad_import`? Pelkkä `import` on monessa kontekstissa komento/avainsana, joten lukijalta voi mennä helposti asiat sekaisin.
___
*[docker-postgis/Dockerfile, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVovGf66m4hhJATVesM:-MVovGf66m4hhJATVesN:bgq4szw) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/4138802715a52e9d408496f26546adf9c4a7d63b/docker-postgis/Dockerfile#L1)):*
> ```
>  mdillon/postgis:9.6
> ```

Tuolla `jore4-graphql-playground` repossa on käytetty `postgis/postgis:12-3.1-alpine` imagea, pitäiskö tässä kenties olla kanssa vähän tuoreempi versio?

**Comment by haphut** [comment]
___
*[create_digiroad_pgdump.sh, line 11 at r2](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVyyyHgDguQxTlD9AWI:-MVyyyHgDguQxTlD9AWJ:b-wig1bd) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/5f4be82fbce82c1e431e138b4b35444f5de3826b/create_digiroad_pgdump.sh#L11)):*
> ```Shell
> set -eu
> 
> DOWNLOAD_TARGET_FILE="${WORK_DIR}/zip/UUSIMAA_R.zip"
> ```

Maybe use the K dataset? A priori that seems easier to use through an API without having to calculate the linear reference lengths in the server or the frontend.

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2)* status: 9 of 13 files reviewed, 4 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

**Review by lassemaatta — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @jarkkoka and @lassemaatta)

**Review by lassemaatta — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2)* status: all files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

**Review by haphut — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2)* status: all files reviewed, 7 unresolved discussions (waiting on @jarkkoka)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MW4wEz_9kXQstcYeR5f:-MW4wEza9zfagfNt3ZV4:b-n86kyf) (no related file):*
Great work!

I'm sorry for the rushed review. I could not find the time yet to run this from start to finish.

---
___
*[build_docker_image.sh, line 3 at r2](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVynu-88fUBVsYw56Gj:-MVynu-88fUBVsYw56Gk:bpe1ult) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/5f4be82fbce82c1e431e138b4b35444f5de3826b/build_docker_image.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> 
> docker build --no-cache -t jore4/postgis-digiroad ./docker-postgis/
> ```

Hmm, I wonder why you used `--no-cache`.
___
*[create_digiroad_pgdump.sh, line 6 at r3](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MW4xVy578QBDsrJRutQ:-MW4xVy578QBDsrJRutR:b-f8mipg) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/0ab4a0bfa459616a52693fe0ab2ec78cb7f9dd8f/create_digiroad_pgdump.sh#L6)):*
> ```Shell
> 
> CWD=$(pwd)
> WORK_DIR="${CWD}/workdir"
> ```

Maybe create this one with `mkdir -p` and drop the `.keep` files? Up to you.
___
*[import_digiroad_links.sh, line 55 at r3](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MW4wMy39-wkrOQLY1_H:-MW4wMy39-wkrOQLY1_I:bl64f6n) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/0ab4a0bfa459616a52693fe0ab2ec78cb7f9dd8f/import_digiroad_links.sh#L55)):*
> ```Shell
>         src.digiroad_id,
>         (
>             SELECT infrastructure_network_type_id
> ```

Hopefully this becomes unnecessary with HSLdevcom/jore4-sql-schema-experiment#13
___
*[docker-postgis/Dockerfile, line 3 at r3](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVzEnDj34HVidvXmyGI:-MVzEnDj34HVidvXmyGJ:b-2n4sfr) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/0ab4a0bfa459616a52693fe0ab2ec78cb7f9dd8f/docker-postgis/Dockerfile#L3)):*
> ```Dockerfile
> FROM postgis/postgis:13-master
> 
> RUN localedef -i fi_FI -c -f UTF-8 -A /usr/share/locale/locale.alias fi_FI.UTF-8
> ```

What is the purpose of these locale changes? I would rather lean towards explicit conversions from Finnish to international/UTC/whatever, where needed.
___
*[sql/transform_dr_links.sql, line 12 at r3](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MW4wrJU2JdFOsEic67x:-MW4wrJU2JdFOsEic67y:b-tgz59s) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/0ab4a0bfa459616a52693fe0ab2ec78cb7f9dd8f/sql/transform_dr_links.sql#L12)):*
> ```TSQL
>     (ST_Dump(src.geom)).geom AS geom_dump
> FROM digiroad_import.dr_links_in src
> WHERE src.kuntakoodi IN (
> ```

It's probably okay to have all of Uusimaa. That way new municipalities are easier to add and maybe U-busses (coming from outside of HSL area into HSL area but not managed by HSL) could be modelled as well.

Having all of Finland might be okay as well, later.

**Review by haphut — COMMENTED** [review]
> Reviewed 7 of 13 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2)* status: all files reviewed, 7 unresolved discussions (waiting on @jarkkoka)

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2)* status: all files reviewed, 7 unresolved discussions (waiting on @haphut and @jarkkoka)

___
*[build_docker_image.sh, line 3 at r2](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVynu-88fUBVsYw56Gj:-Ma3RWnKEg5NhdugcSFU:b-ea12tp) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/5f4be82fbce82c1e431e138b4b35444f5de3826b/build_docker_image.sh#L3)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Hmm, I wonder why you used `--no-cache`.
</blockquote></details>

Had a look at Dockerfile. There seems to be nothing that would really benefit or require --no-cache option. So, you're right. It can be removed.
___
*[create_digiroad_pgdump.sh, line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVouEDg-gmwe24gD9e9:-MVpy6Ae0-HmyfaFfYrm:bjmnkjt) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/4138802715a52e9d408496f26546adf9c4a7d63b/create_digiroad_pgdump.sh#L31)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

kenties `|| true` voisi korvata nuo `set +e` lipun nollailut?
</blockquote></details>

Kiitos tästä. Lipun nollailu tuntuikin vähän kömpelöltä.
___
*[create_digiroad_pgdump.sh, line 48 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVovc-m2v-sMPvf_o5P:-MVpyIQjCWld7Q2T-b3A:b-1u49wl) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/4138802715a52e9d408496f26546adf9c4a7d63b/create_digiroad_pgdump.sh#L48)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> import
> ```

Voisko tää olla vaikka `dr_import` tai `digiroad_import`? Pelkkä `import` on monessa kontekstissa komento/avainsana, joten lukijalta voi mennä helposti asiat sekaisin.
</blockquote></details>

Jep, prefix olisi selkeämpi. Teen muutoksen.
___
*[create_digiroad_pgdump.sh, line 11 at r2](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVyyyHgDguQxTlD9AWI:-Ma4gPvR6oaMVbjxHFzm:b21mj49) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/5f4be82fbce82c1e431e138b4b35444f5de3826b/create_digiroad_pgdump.sh#L11)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Maybe use the K dataset? A priori that seems easier to use through an API without having to calculate the linear reference lengths in the server or the frontend.
</blockquote></details>

Will change to K dataset.
___
*[create_digiroad_pgdump.sh, line 6 at r3](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MW4xVy578QBDsrJRutQ:-Ma4gM0f2WfAdN5xP8_E:b-1lfvng) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/0ab4a0bfa459616a52693fe0ab2ec78cb7f9dd8f/create_digiroad_pgdump.sh#L6)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Maybe create this one with `mkdir -p` and drop the `.keep` files? Up to you.
</blockquote></details>

Will do this.
___
*[import_digiroad_links.sh, line 55 at r3](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MW4wMy39-wkrOQLY1_H:-Ma4gX3l62oey6SgzhTo:bb5zec7) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/0ab4a0bfa459616a52693fe0ab2ec78cb7f9dd8f/import_digiroad_links.sh#L55)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Hopefully this becomes unnecessary with HSLdevcom/jore4-sql-schema-experiment#13
</blockquote></details>

Not doing changes until then.
___
*[docker-postgis/Dockerfile, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVovGf66m4hhJATVesM:-MVpyMHH5wRiu_zQGjhb:bmzkk65) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/4138802715a52e9d408496f26546adf9c4a7d63b/docker-postgis/Dockerfile#L1)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
>  mdillon/postgis:9.6
> ```

Tuolla `jore4-graphql-playground` repossa on käytetty `postgis/postgis:12-3.1-alpine` imagea, pitäiskö tässä kenties olla kanssa vähän tuoreempi versio?
</blockquote></details>

Kokeilin alkuun ehdottamallasi imagella, mutten saanut sitä helposti ja nopeasti tunkattua kuntoon siten, että toimisi muiden Dockerfilessa olevien määrittelyiden kanssa. Sinänsä Docker-containerissa tehtävät operaatiot eivät nykyisellään vaadi uudempia PostGIS-funktioita, kuin mitä tämä v9.6 tarjoaa. Mutta voisin ehkä vielä yrittää päivittää perusimagea.
___
*[docker-postgis/Dockerfile, line 3 at r3](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVzEnDj34HVidvXmyGI:-Ma4hbhR-E9Bne1IZtee:b4dn4hg) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/0ab4a0bfa459616a52693fe0ab2ec78cb7f9dd8f/docker-postgis/Dockerfile#L3)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

What is the purpose of these locale changes? I would rather lean towards explicit conversions from Finnish to international/UTC/whatever, where needed.
</blockquote></details>

The purpose is to ascertain that strings (e.g. road names) with scandinavian characters are handled properly while importing shapefiles into database.
___
*[sql/transform_dr_links.sql, line 12 at r3](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MW4wrJU2JdFOsEic67x:-Ma4gwtVC2uiFw5npaGS:b-124ll8) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/0ab4a0bfa459616a52693fe0ab2ec78cb7f9dd8f/sql/transform_dr_links.sql#L12)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

It's probably okay to have all of Uusimaa. That way new municipalities are easier to add and maybe U-busses (coming from outside of HSL area into HSL area but not managed by HSL) could be modelled as well.

Having all of Finland might be okay as well, later.
</blockquote></details>

The aim was to ease processing in QGIS and other tools with reduced dataset. Will see, whether filtering is good or bad...

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 8 of 8 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2)* status: all files reviewed, 7 unresolved discussions (waiting on @haphut and @jarkkoka)

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2)* status: 10 of 13 files reviewed, 8 unresolved discussions (waiting on @haphut, @jarkkoka, and @lassemaatta)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MaE7Nkc7WUzEY4RDtI6:-MaE7Nkc7WUzEY4RDtI7:b-u1xqkd) (no related file):*
I updated pull request by copying all fields from DR_LINKKI_K shapefile into pg_dump file. Thus, no properties is lost in the first stage of transformation which makes the whole transformation process more flexible. I also kept the original Finnish column names in order to not have obfuscation penalty (caused by Finnish -> English translation) while consulting Digiroad documentation.

---

**Review by haphut — COMMENTED** [review]
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @haphut and @jarkkoka)

___
*[docker-postgis/Dockerfile, line 3 at r3](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MVzEnDj34HVidvXmyGI:-McDq3-j84sv60ER-MuU:b-ucfknh) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/0ab4a0bfa459616a52693fe0ab2ec78cb7f9dd8f/docker-postgis/Dockerfile#L3)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The purpose is to ascertain that strings (e.g. road names) with scandinavian characters are handled properly while importing shapefiles into database.
</blockquote></details>

Thanks!

**Review by haphut — APPROVED** [review]
> Reviewed 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @haphut and @jarkkoka)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/2#-MaE7Nkc7WUzEY4RDtI6:-McDqaDT5rz3v9Ie90te:bu5m2uc) (no related file):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I updated pull request by copying all fields from DR_LINKKI_K shapefile into pg_dump file. Thus, no properties is lost in the first stage of transformation which makes the whole transformation process more flexible. I also kept the original Finnish column names in order to not have obfuscation penalty (caused by Finnish -> English translation) while consulting Digiroad documentation.
</blockquote></details>

Thank you! Looks nice.

I'm sorry about the delay even after notifying me.

For some reason I could not find this PR listed in Reviewable but could navigate into it from GitHub.

---

**Pull request merged**
