### PR TITLE
Add script to export Digiroad links as MBTiles file.

### PR DESCRIPTION
**Pull request by jarkkoka**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9)

### CODE REVIEW

**Review by tk-vincit — COMMENTED** [review]
Minor comments. Maybe also someone else could take a look at this.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9#-:-MkGLDnC7hbhGUF_iL44:bjgura1)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @tk-vincit)

___
*[export_mbtiles_dr_linkki_k.sh, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9#-MkGG-pk2eSB3UutbZ9W:-MkGG-pk2eSB3UutbZ9X:bafh68v) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/a92d0091f6b267edaafe31835369baf47d506364/export_mbtiles_dr_linkki_k.sh#L16)):*
> ```Shell
> 
> MBTILES_OUTPUT_DIR="${WORK_DIR}/mbtiles"
> SHP_OUTPUT_DIR="${MBTILES_OUTPUT_DIR}/shp_input"
> ```

Output dir equals input? 🤔 Don't know if this is correct or not, but at least this is a bit confusing.
Same on the row below
___
*[docker-postgis/Dockerfile, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9#-MkGKW3S7SoC78kApE1E:-MkGKW3S7SoC78kApE1F:b-cwkoh7) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/a92d0091f6b267edaafe31835369baf47d506364/docker-postgis/Dockerfile#L21)):*
> ```Dockerfile
> # Remove the temp directory and unneeded packages used to build tippecanoe.
> WORKDIR /
> RUN rm -rf /tmp/tippecanoe-src \
> ```

I'm not docker expert, but is it really useful to remove these in Dockerfile? As far as I have understood each command here creates new layer for docker image, so the files will be in docker image even if they are "removed" here.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @tk-vincit)

___
*[export_mbtiles_dr_linkki_k.sh, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9#-MkGG-pk2eSB3UutbZ9W:-MkGONi5AJlbkpvItqWw:b-hszqu2) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/a92d0091f6b267edaafe31835369baf47d506364/export_mbtiles_dr_linkki_k.sh#L16)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Output dir equals input? 🤔 Don't know if this is correct or not, but at least this is a bit confusing.
Same on the row below
</blockquote></details>

Those input directories are actually subdirectories inside MBTiles output directory. The final `.mbtiles` file will be put into `workdir/mbtiles` while the intermediary shapefiles and `.geojson` file will be put into `workdir/mbtiles/shp_input` and `workdir/mbtiles/geojson_input` respectively.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @tk-vincit)

___
*[export_mbtiles_dr_linkki_k.sh, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9#-MkGG-pk2eSB3UutbZ9W:-MkGPayR-GKrQfdygRDd:b-va0cmj) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/a92d0091f6b267edaafe31835369baf47d506364/export_mbtiles_dr_linkki_k.sh#L16)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Those input directories are actually subdirectories inside MBTiles output directory. The final `.mbtiles` file will be put into `workdir/mbtiles` while the intermediary shapefiles and `.geojson` file will be put into `workdir/mbtiles/shp_input` and `workdir/mbtiles/geojson_input` respectively.
</blockquote></details>

Okay...

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @tk-vincit)

___
*[docker-postgis/Dockerfile, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9#-MkGKW3S7SoC78kApE1E:-MkGS_qE40cgxWBbKtPp:b-4h1aii) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/a92d0091f6b267edaafe31835369baf47d506364/docker-postgis/Dockerfile#L21)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I'm not docker expert, but is it really useful to remove these in Dockerfile? As far as I have understood each command here creates new layer for docker image, so the files will be in docker image even if they are "removed" here.
</blockquote></details>

The intention is to make Docker image slimmer. See for reference:
* https://www.ianlewis.org/en/creating-smaller-docker-images
* https://github.com/valeriansaliou/sonic/issues/72

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @jarkkoka, @pallost, and @tk-vincit)

___
*[docker-postgis/Dockerfile, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9#-MkGKW3S7SoC78kApE1E:-MkGVN69DA1py6mh-H81:b-ryoiis) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/a92d0091f6b267edaafe31835369baf47d506364/docker-postgis/Dockerfile#L21)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The intention is to make Docker image slimmer. See for reference:
* https://www.ianlewis.org/en/creating-smaller-docker-images
* https://github.com/valeriansaliou/sonic/issues/72
</blockquote></details>

these cleanup commands should be called from the same RUN command as the `make install`

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @jarkkoka, @pallost, and @tk-vincit)

___
*[docker-postgis/Dockerfile, line 28 at r2](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9#-MkGqa614raYyENRb_kx:-MkGqa614raYyENRb_ky:bc634mm) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/d99fdc6ba2b90ded02fcd62195081dd4f462a7d7/docker-postgis/Dockerfile#L28)):*
> ```Dockerfile
> 
> RUN cp /usr/share/zoneinfo/Europe/Helsinki /etc/localtime \
>  && echo "Europe/Helsinki" > /etc/timezone
> ```

you already have this available and environment variable. Could just do:
```
RUN cp "/usr/share/zoneinfo/${TZ}" /etc/localtime \
 && echo "${TZ}" > /etc/timezone

```
___
*[docker-postgis/Dockerfile, line 32 at r2](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/9#-MkGqnjZ0Ic-eOQnU1wu:-MkGqnj_E1UBOlrFpAcx:b8jp0b) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/d99fdc6ba2b90ded02fcd62195081dd4f462a7d7/docker-postgis/Dockerfile#L32)):*
> ```Dockerfile
> ADD /docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
> 
> ENV TZ Europe/Helsinki
> ```

as these environment variables are static, to optimize docker caching, they should be defined rather in the beginning of the Dockerfile. Because now every time the docker-entrypoint-initdb.d folder contents change, all these ENV* commands create new layers every time

**Pull request merged**
