### PR TITLE
Infra link export

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13)

Closes https://github.com/HSLdevcom/jore4/issues/491

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[set_env_vars.sh, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlA9o399xnIN2KZrzoB:-MlA9o399xnIN2KZrzoC:b-mygs68) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/set_env_vars.sh#L20)):*
> ```Shell
> export PSQL='exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U digiroad -d digiroad --no-password'
> export PG_WAIT='exec /wait-pg.sh "$DB_NAME" "$POSTGRES_PORT_5432_TCP_ADDR" "$POSTGRES_PORT_5432_TCP_PORT"'
> export PG_WAIT_LOCAL='exec /wait-pg.sh "$DB_NAME" localhost "$POSTGRES_PORT_5432_TCP_PORT"'
> ```

These are bash aliases instead of env variables, right? So the name of this file is a bit confusing. Anyway, that is not in scope of this PR so this is fine for me. But maybe better name would be e.g. `initialize_bash_environment.sh`?
___
*[upload_to_azure.sh, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlA9A1F1gOBdrtb_9Wp:-MlA9A1F1gOBdrtb_9Wq:b-ikc40k) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/upload_to_azure.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Maybe this script should be documented to README?
Maybe there should be also warning that this uploads ALL .sql/.json files from workdir/pgdump directory to azure blob storage.

When this script is intented to be used?
___
*[upload_to_azure.sh, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlA8lTgCL_V7A5SyhA7:-MlA8lTgCL_V7A5SyhA8:b-kr2j44) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/upload_to_azure.sh#L21)):*
> ```Shell
>   --account-name "jore4storage" \
>   --auth-mode "login" \
>   --container "jore4-digiroad"  
> ```

Trailing whitespace
___
*[sql/select_infra_links.sql, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlA8R-v1St3BNd40cfb:-MlA8R-v1St3BNd40cfc:bopnsnt) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/sql/select_infra_links.sql#L10)):*
> ```TSQL
>             WHEN source.ajosuunta = 3 THEN 'backward'
>             WHEN source.ajosuunta = 4 THEN 'forward'
>             ELSE 'unknown'
> ```

just a question: do we want to use 'unknown' (string) value or NULL?
___
*[sql/select_infra_links.sql, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlA8ZJfCM8wVwFPg8bT:-MlA8ZJfCM8wVwFPg8bU:bp6vj0d) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/sql/select_infra_links.sql#L14)):*
> ```TSQL
>         ST_Length(source.geom) as estimated_length_in_metres
>     FROM :schema.dr_linkki source
> ) result
> ```

Reviewable shows just two rectangles here - is there encoding issue?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @jarkkoka and @tk-vincit)

___
*[set_env_vars.sh, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlA9o399xnIN2KZrzoB:-MlABHDKA66PKJTEl9KN:b-drlmmj) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/set_env_vars.sh#L20)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

These are bash aliases instead of env variables, right? So the name of this file is a bit confusing. Anyway, that is not in scope of this PR so this is fine for me. But maybe better name would be e.g. `initialize_bash_environment.sh`?
</blockquote></details>

other branches also use this file so I wouldn't start renaming it for now...
___
*[sql/select_infra_links.sql, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlA8R-v1St3BNd40cfb:-MlACXjH5EHw1JBFKikh:bm4cbg3) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/sql/select_infra_links.sql#L10)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

just a question: do we want to use 'unknown' (string) value or NULL?
</blockquote></details>

I couldn't find a way to use `RAISEERROR` here :(
___
*[sql/select_infra_links.sql, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlA8ZJfCM8wVwFPg8bT:-MlACT_r9wbs5b9Ih3td:bqvyti3) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/sql/select_infra_links.sql#L14)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Reviewable shows just two rectangles here - is there encoding issue?
</blockquote></details>

there was no newline at the end. Fixed it
___
*[upload_to_azure.sh, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlA9A1F1gOBdrtb_9Wp:-MlABNsuCuixMvrY5f7i:bvqrz0p) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/upload_to_azure.sh#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Maybe this script should be documented to README?
Maybe there should be also warning that this uploads ALL .sql/.json files from workdir/pgdump directory to azure blob storage.

When this script is intented to be used?
</blockquote></details>

good point, I'll add it to README. Maybe I'll also limit better what files are to be uploaded to azure; *.sql and *.json are too wide
___
*[upload_to_azure.sh, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlA8lTgCL_V7A5SyhA7:-MlACbuW4jaB2qAYE-6i:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/upload_to_azure.sh#L21)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Trailing whitespace
</blockquote></details>

Done.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @jarkkoka and @tk-vincit)

___
*[sql/select_infra_links.sql, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlA8R-v1St3BNd40cfb:-MlAEvn8-eECClFlGQqo:bezarud) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/sql/select_infra_links.sql#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I couldn't find a way to use `RAISEERROR` here :(
</blockquote></details>

filtering these from the WHERE clause

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13)* status: 4 of 6 files reviewed, 10 unresolved discussions (waiting on @jarkkoka, @pallost, and @tk-vincit)

___
*[export_infra_network_json.sh, line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlAEHs28Zm4dETKsiIl:-MlAEHs28Zm4dETKsiIm:b-x0hswj) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/export_infra_network_json.sh#L15)):*
> ```
> infra_network_
> ```

I would rename this to `infra_network_digiroad_r` to separate file from other upcoming infra sources (e.g. tram, train) and to distinguish from Digiroad K material.
___
*[export_infra_network_json.sh, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlACHZD7QgCgIMNf2Y1:-MlACHZD7QgCgIMNf2Y2:bx54wp8) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/export_infra_network_json.sh#L18)):*
> ```
> workdir/pgdump:/tmp/pgdump
> ```

Replace with: `workdir/json:tmp/json`
___
*[export_infra_network_json.sh, line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlAC7TsEYmgZvKJFzYA:-MlAC7TsEYmgZvKJFzYB:ba0eyhe) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/export_infra_network_json.sh#L19)):*
> ```
> select_infra_links.sql
> ```

Rename this file to `select_infra_links_as_json.sql`
___
*[README.md, line 42 at r2](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlAEfS92M61J5bp64w3:-MlAEfS92M61J5bp64w4:b-9twzg0) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/e9acdb4600d307df3f061618548555b19a619c5c/README.md#L42)):*
> ```
> upload_dumps_to_azure.sh
> ```

I would rename this to `upload_infra_links_to_azure.sh` or something similar to describe more what is going to be uploaded.
___
*[set_env_vars.sh, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlA9o399xnIN2KZrzoB:-MlAClhVD3-izrie1UEY:b-vtnamr) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/set_env_vars.sh#L20)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

other branches also use this file so I wouldn't start renaming it for now...
</blockquote></details>

Indeed changing the structure is out of scope of this PR.
___
*[sql/select_infra_links.sql, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlAD3lU3UPO1jEskKWT:-MlAD3lV7fjsjNugc7N3:b1aw553) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/sql/select_infra_links.sql#L4)):*
> ```
> source.link_id as external_link_id,
> ```

IMO there should also be external system ID for Digiroad but I don't yet know how to express it. Need to consult jschummer.
___
*[sql/select_infra_links.sql, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlA8R-v1St3BNd40cfb:-MlADmyI0cu07oUxtgAN:b-fq7qkb) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/sql/select_infra_links.sql#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I couldn't find a way to use `RAISEERROR` here :(
</blockquote></details>

Add a WHERE predicate to filter out rows that have no correct `ajosuunta`.
___
*[upload_to_azure.sh, line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlABuq0DlINC8-zlwbt:-MlABuq0DlINC8-zlwbu:be0a93c) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/upload_to_azure.sh#L17)):*
> ```
> /workdir/pgdump/*.json
> ```

Obviously JSON files should not be output into `pgdump` directory.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13)* status: 4 of 6 files reviewed, 9 unresolved discussions (waiting on @jarkkoka and @tk-vincit)

___
*[export_infra_network_json.sh, line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlAEHs28Zm4dETKsiIl:-MlDrznZ-vMkM3wLbriZ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/export_infra_network_json.sh#L15)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> infra_network_
> ```

I would rename this to `infra_network_digiroad_r` to separate file from other upcoming infra sources (e.g. tram, train) and to distinguish from Digiroad K material.
</blockquote></details>

Done.
___
*[export_infra_network_json.sh, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlACHZD7QgCgIMNf2Y1:-MlDsCWv6hmsOEwvcIB_:buormks) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/export_infra_network_json.sh#L18)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> workdir/pgdump:/tmp/pgdump
> ```

Replace with: `workdir/json:tmp/json`
</blockquote></details>

I'd rather just rename the folder as "output" as there's no need to distinguish between the different types of outputs
___
*[export_infra_network_json.sh, line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlAC7TsEYmgZvKJFzYA:-MlDsdja-ez8mQFEh-_E:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/export_infra_network_json.sh#L19)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> select_infra_links.sql
> ```

Rename this file to `select_infra_links_as_json.sql`
</blockquote></details>

Done.
___
*[README.md, line 42 at r2](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlAEfS92M61J5bp64w3:-MlDsfJ8-Ev8VhvmxVZJ:by5ch7s) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/e9acdb4600d307df3f061618548555b19a619c5c/README.md#L42)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> upload_dumps_to_azure.sh
> ```

I would rename this to `upload_infra_links_to_azure.sh` or something similar to describe more what is going to be uploaded.
</blockquote></details>

I'd rather call this upload_outputs_to_azure.sh, because the aim is to store all the output files in blob storage to enable them to be easily transferred between team members
___
*[sql/select_infra_links.sql, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlAD3lU3UPO1jEskKWT:-MlDt7CA2EOaqviAyw76:bi0m450) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/sql/select_infra_links.sql#L4)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> source.link_id as external_link_id,
> ```

IMO there should also be external system ID for Digiroad but I don't yet know how to express it. Need to consult jschummer.
</blockquote></details>

I agree, I've been thinking the same. How about "digiroad_r"? I started a conversation thread about this on slack
___
*[upload_to_azure.sh, line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlABuq0DlINC8-zlwbt:-MlDt605-ryLh4r8a0Xr:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/upload_to_azure.sh#L17)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> /workdir/pgdump/*.json
> ```

Obviously JSON files should not be output into `pgdump` directory.
</blockquote></details>

Done.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13)* status: all files reviewed, 11 unresolved discussions (waiting on @jarkkoka, @pallost, and @tk-vincit)

___
*[export_infra_network_json.sh, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlACHZD7QgCgIMNf2Y1:-MlFe2JC8u9Q67xuYYjx:b-fbekhn) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/export_infra_network_json.sh#L18)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd rather just rename the folder as "output" as there's no need to distinguish between the different types of outputs
</blockquote></details>

That kind of overly general folder name is not really helpful but instead confusing (harmful) since every subdirectory inside `workdir` denotes some kind of output. The other directories (`pgdump`, `mbtiles`, `shp`) are also outputs for different purposes.
___
*[export_infra_network_json.sh, line 16 at r4](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlFdMlc1mMKR88VSQn4:-MlFdMlc1mMKR88VSQn5:bjxylvo) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/ed302f7d45b10e5cb821b3439eca9d8be1b5da9f/export_infra_network_json.sh#L16)):*
> ```
> /output
> ```

This folder name is not really helpful since basically every subdirectory inside `workdir` denotes some kind of output. When creating the directory structure I've sticked to naming subdirectories according to file extensions that are produced to ease finding relevant output. Hence, I would *still* suggest `json` as directory name for this type of output. 
___
*[README.md, line 42 at r2](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlAEfS92M61J5bp64w3:-MlFf7vF2HZK5WmuaNtD:b-atqkvb) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/e9acdb4600d307df3f061618548555b19a619c5c/README.md#L42)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd rather call this upload_outputs_to_azure.sh, because the aim is to store all the output files in blob storage to enable them to be easily transferred between team members
</blockquote></details>

There are many kind of outputs produced in this repository. I would suggest being explicit enough in naming in order to not make things too hard to maintain.
___
*[sql/select_infra_links.sql, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlAD3lU3UPO1jEskKWT:-MlFfjxj95gkQgMa-v-c:bfl0x1y) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/6ac285e83ef711a215c185d5a6bf26077fcded3b/sql/select_infra_links.sql#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I agree, I've been thinking the same. How about "digiroad_r"? I started a conversation thread about this on slack
</blockquote></details>

Yup. That might be a good starting point.
___
*[sql/select_infra_links_as_json.sql, line 13 at r4](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlFfU3c-hodT3pEi_Mr:-MlFfU3c-hodT3pEi_Ms:b-b72uvq) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/ed302f7d45b10e5cb821b3439eca9d8be1b5da9f/sql/select_infra_links_as_json.sql#L13)):*
> ```
> WHERE source.ajosuunta IN (2, 3, 4) -- filter out possibly invalid links
> ```

Nice :+1:

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13)* status: all files reviewed, 11 unresolved discussions (waiting on @jarkkoka, @pallost, and @tk-vincit)

___
*[export_infra_network_json.sh, line 16 at r4](https://reviewable.io/reviews/hsldevcom/jore4-digiroad-import-experiment/13#-MlFdMlc1mMKR88VSQn4:-MlFhKhoB1CmwKxaEl6j:b-tghl2g) ([raw file](https://github.com/hsldevcom/jore4-digiroad-import-experiment/blob/ed302f7d45b10e5cb821b3439eca9d8be1b5da9f/export_infra_network_json.sh#L16)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> /output
> ```

This folder name is not really helpful since basically every subdirectory inside `workdir` denotes some kind of output. When creating the directory structure I've sticked to naming subdirectories according to file extensions that are produced to ease finding relevant output. Hence, I would *still* suggest `json` as directory name for this type of output. 
</blockquote></details>

Other possible folder names could be e.g. `infra`, `jore4`, `jore4_infra`, `jore4_infrastructure_network` or something similar which is appropriate and practical.

**Pull request closed without merging**
